version: '3.6'

services:

  fluxodb:
    image: postgres

  pgadmin-compose:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

volumes:
  postgres_data:
  pgadmin_data:
  portainer_data:

networks: 
  postgres-network:
    driver: bridge




  

